### ISSUE TITLE
AM stations in the preset

### ISSUE THREAD

**Issue by mtv-alex** [AmateurAudioDude/FM-DX-Webserver-Plugin-Button-Presets#1]
When saving the AM station to a preset, it does not fully save the frequency. And if you click on the preset (in my case, 0.792 MHz), the frequency is rounded up to 0.800 MHz.

![image](https://github.com/user-attachments/assets/5102e6ff-a86a-422c-b96f-48cbb6ffc36f)

**Comment by AmateurAudioDude** [comment]
Fixed in latest update.
